### ISSUE TITLE
API token published

### ISSUE THREAD

**Issue by ilevn** [Red-Ravens/soccer-updater#1]
Hey, 
I just wanted to point out that you seem to have [published](https://github.com/Red-Ravens/soccer-updater/blob/master/updater.py#L38) your Pushbullet API token in the last [commit](https://github.com/Red-Ravens/soccer-updater/commit/d5a04b6cddfd2d0b661bf26e60efa7945db3b578).
I suggest that you immidiately revoke said token as it gives everyone access to your account. You should also hard reset your current HEAD to the last commit and force push afterwords. This ensures that the old token gets deleted from the commit history.

Cheers,
Nils T.

**Comment by Red-Ravens** [comment]
Thanks for the heads up! How do I reset to the current head and force push?

**Comment by ilevn** [comment]
Hi,
you can reset your HEAD to the last commit by finding the sha1-commit ID and executing `git reset --hard <sha1-commit-id>` and `git push -f` afterwords. The sha1-commit ID of your latest commit is `17822be43b918f4832437f938e78d085f46f63ce`. Keep in mind that reseting the HEAD to the commit on the 17th of August gets rid of of every other commit that was pushed to the remote branch after this date. ([commit d5a04b6](https://github.com/Red-Ravens/soccer-updater/commit/d5a04b6cddfd2d0b661bf26e60efa7945db3b578) and [commit 25b8d7a](https://github.com/Red-Ravens/soccer-updater/commit/25b8d7a3b43cc11df08679af7058ed22e96b5961))
I recommend that you save the changes in these commits before you reset and simply re-push them after you cleaned up your commit history with the involved token. You should also `git stash` all local changes. This prevents any unintended loses.

**Comment by Red-Ravens** [comment]
Is there a way to do this on GitHub? I've just been uploading files instead of doing it via command line

**Comment by ilevn** [comment]
There is currently no way of resetting the HEAD on the GitHub web UI, sadly. If you can't reset the HEAD, just revoke the token and you should be all set.

**Comment by Red-Ravens** [comment]
Yep that's what I did. Thanks again!

**Comment by ilevn** [comment]
You're welcome :-)
